/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.coolcow.arpiti.gui;

import java.awt.Component;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.RowFilter.Entry;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;
import org.coolcow.arpiti.backend.Backend;
import org.coolcow.arpiti.backend.rpttailer.RptTailerListener;
import org.coolcow.arpiti.backend.rptline.AbstractRptLine;
import org.coolcow.arpiti.gui.renderer.AbstractRptLineRenderer;

/**
 *
 * @author jruiz
 */
public final class MainFrame extends javax.swing.JFrame {

    public final static String OUTPUT_DATE_FORMAT = "HH:mm:ss";
    private final RptLineTableModel model = new RptLineTableModel();
    private File rptFile = null;
    private boolean autoscroll = true;
    private final TableRowSorter<RptLineTableModel> sorter = new TableRowSorter<>(model);
    private AbstractRptLine popLine = null;
    
    private static final Logger LOG = Logger.getLogger(MainFrame.class);
    private static MainFrame INSTANCE;

    public static MainFrame getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new MainFrame();
        }
        return INSTANCE;
    }
    /**
     * Creates new form NewJFrame
     */
    private MainFrame() {
        initComponents();

        sorter.setRowFilter(new RowFilterImpl());
        tblLines.setRowSorter(sorter);
        tblLines.setAutoCreateRowSorter(false);
        tblLines.setDefaultRenderer(Date.class, new RptTableDateCellRenderer());
        tblLines.addMouseListener(new RptTableMouseListener());
        tblLines.getSelectionModel().addListSelectionListener(new RptTableSelectionListener());

        final TableColumnModel columnModel = tblLines.getColumnModel();
        columnModel.getColumn(RptLineTableModel.COLUMN_NUMBER).setPreferredWidth(60);
        columnModel.getColumn(RptLineTableModel.COLUMN_TIME).setPreferredWidth(60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pumTableitem = new javax.swing.JPopupMenu();
        mniCopy = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panMain = new javax.swing.JPanel();
        panProgress = new javax.swing.JPanel();
        pgbLines = new javax.swing.JProgressBar();
        tgbAutoScroll = new javax.swing.JToggleButton();
        panInfo = new javax.swing.JPanel();
        panTable = new javax.swing.JPanel();
        scrTable = new javax.swing.JScrollPane();
        tblLines = new CorrectLayoutJTable();
        panRight = new javax.swing.JPanel();
        panFilter = new javax.swing.JPanel();
        txtFilterContent = new javax.swing.JTextField();
        panTypes = new javax.swing.JPanel();
        cbxFilterNull = new javax.swing.JCheckBox();
        cbxFilterDwDebugFps = new javax.swing.JCheckBox();
        cbxFilterError = new javax.swing.JCheckBox();
        cbxFilterLocalityEvent = new javax.swing.JCheckBox();
        cbxFilterStartingLogin = new javax.swing.JCheckBox();
        cbxFilterLoginAttempt = new javax.swing.JCheckBox();
        cbxFilterLoginPublishing = new javax.swing.JCheckBox();
        cbxFilterLoginLoaded = new javax.swing.JCheckBox();
        cbxFilterHive = new javax.swing.JCheckBox();
        cbxFilterWrite = new javax.swing.JCheckBox();
        cbxFilterReadWrite = new javax.swing.JCheckBox();
        cbxFilterDelete = new javax.swing.JCheckBox();
        cbxFilterDisconnectStartI = new javax.swing.JCheckBox();
        cbxFilterCleanup = new javax.swing.JCheckBox();
        cbxFilterPdeath = new javax.swing.JCheckBox();
        cbxFilterSecondHandZombieInitialized = new javax.swing.JCheckBox();
        cbxFilterObj = new javax.swing.JCheckBox();
        btnFilterApply = new javax.swing.JButton();
        cbFilterContent = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        defaultCoordinateInfoComponent1 = new org.coolcow.arpiti.gui.DefaultCoordinateInfoComponent();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnLoadRpt = new javax.swing.JButton();
        txtRptPath = new javax.swing.JTextField();
        tgbResume = new javax.swing.JToggleButton();

        mniCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/coolcow/arpiti/gui/copy.png"))); // NOI18N
        mniCopy.setText("copy to clipboard");
        mniCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCopyActionPerformed(evt);
            }
        });
        pumTableitem.add(mniCopy);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("aRPiTi (RPT analysis tool)  - by coolcow [ALPHA version]");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panMain.setLayout(new java.awt.GridBagLayout());

        panProgress.setLayout(new java.awt.GridBagLayout());

        pgbLines.setFocusable(false);
        pgbLines.setPreferredSize(new java.awt.Dimension(146, 20));
        pgbLines.setString("0 lines");
        pgbLines.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panProgress.add(pgbLines, gridBagConstraints);

        tgbAutoScroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/coolcow/arpiti/gui/autoscroll.png"))); // NOI18N
        tgbAutoScroll.setSelected(true);
        tgbAutoScroll.setFocusPainted(false);
        tgbAutoScroll.setFocusable(false);
        tgbAutoScroll.setMaximumSize(new java.awt.Dimension(25, 25));
        tgbAutoScroll.setMinimumSize(new java.awt.Dimension(25, 25));
        tgbAutoScroll.setPreferredSize(new java.awt.Dimension(25, 25));
        tgbAutoScroll.setRequestFocusEnabled(false);
        tgbAutoScroll.setRolloverEnabled(false);
        tgbAutoScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbAutoScrollActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panProgress.add(tgbAutoScroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        panMain.add(panProgress, gridBagConstraints);

        panInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Details about selected row"));
        panInfo.setMaximumSize(new java.awt.Dimension(350, 23));
        panInfo.setMinimumSize(new java.awt.Dimension(350, 23));
        panInfo.setPreferredSize(new java.awt.Dimension(350, 23));
        panInfo.setLayout(new javax.swing.BoxLayout(panInfo, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        panMain.add(panInfo, gridBagConstraints);

        panTable.setLayout(new java.awt.GridBagLayout());

        tblLines.setModel(model);
        tblLines.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblLines.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLines.getTableHeader().setReorderingAllowed(false);
        scrTable.setViewportView(tblLines);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panTable.add(scrTable, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        panMain.add(panTable, gridBagConstraints);
        panTable.getAccessibleContext().setAccessibleName("");

        panRight.setLayout(new java.awt.GridBagLayout());

        panFilter.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));
        panFilter.setLayout(new java.awt.GridBagLayout());

        txtFilterContent.setMinimumSize(new java.awt.Dimension(100, 23));
        txtFilterContent.setPreferredSize(new java.awt.Dimension(100, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        panFilter.add(txtFilterContent, gridBagConstraints);

        panTypes.setBorder(javax.swing.BorderFactory.createTitledBorder("Types"));
        panTypes.setLayout(new java.awt.GridLayout(4, 0));

        cbxFilterNull.setSelected(true);
        cbxFilterNull.setText("<none>");
        panTypes.add(cbxFilterNull);

        cbxFilterDwDebugFps.setSelected(true);
        cbxFilterDwDebugFps.setText("DW_DEBUG FPS");
        panTypes.add(cbxFilterDwDebugFps);

        cbxFilterError.setSelected(true);
        cbxFilterError.setText("ERROR");
        panTypes.add(cbxFilterError);

        cbxFilterLocalityEvent.setSelected(true);
        cbxFilterLocalityEvent.setText("Locality Event");
        panTypes.add(cbxFilterLocalityEvent);

        cbxFilterStartingLogin.setSelected(true);
        cbxFilterStartingLogin.setText("STARTING LOGIN");
        panTypes.add(cbxFilterStartingLogin);

        cbxFilterLoginAttempt.setSelected(true);
        cbxFilterLoginAttempt.setText("LOGIN ATTEMPT");
        panTypes.add(cbxFilterLoginAttempt);

        cbxFilterLoginPublishing.setSelected(true);
        cbxFilterLoginPublishing.setText("LOGIN PUBLISHING");
        panTypes.add(cbxFilterLoginPublishing);

        cbxFilterLoginLoaded.setSelected(true);
        cbxFilterLoginLoaded.setText("LOGIN LOADED");
        panTypes.add(cbxFilterLoginLoaded);

        cbxFilterHive.setSelected(true);
        cbxFilterHive.setText("HIVE");
        panTypes.add(cbxFilterHive);

        cbxFilterWrite.setSelected(true);
        cbxFilterWrite.setText("WRITE");
        panTypes.add(cbxFilterWrite);

        cbxFilterReadWrite.setSelected(true);
        cbxFilterReadWrite.setText("READ/WRITE");
        panTypes.add(cbxFilterReadWrite);

        cbxFilterDelete.setSelected(true);
        cbxFilterDelete.setText("DELETE");
        panTypes.add(cbxFilterDelete);

        cbxFilterDisconnectStartI.setSelected(true);
        cbxFilterDisconnectStartI.setText("DISCONNECT START (i)");
        panTypes.add(cbxFilterDisconnectStartI);

        cbxFilterCleanup.setSelected(true);
        cbxFilterCleanup.setText("CLEANUP");
        panTypes.add(cbxFilterCleanup);

        cbxFilterPdeath.setSelected(true);
        cbxFilterPdeath.setText("PDEATH");
        panTypes.add(cbxFilterPdeath);

        cbxFilterSecondHandZombieInitialized.setSelected(true);
        cbxFilterSecondHandZombieInitialized.setText("SECOND HAND ZOMBIE...");
        panTypes.add(cbxFilterSecondHandZombieInitialized);

        cbxFilterObj.setSelected(true);
        cbxFilterObj.setText("OBJ");
        panTypes.add(cbxFilterObj);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        panFilter.add(panTypes, gridBagConstraints);

        btnFilterApply.setText("apply to all rows");
        btnFilterApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterApplyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        panFilter.add(btnFilterApply, gridBagConstraints);

        cbFilterContent.setText("content:");
        cbFilterContent.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cbFilterContent.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        panFilter.add(cbFilterContent, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panRight.add(panFilter, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 6, 5);
        panMain.add(panRight, gridBagConstraints);

        jTabbedPane1.addTab("content table", panMain);

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 193));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("players"));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 193));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jRadioButton1.setText("all");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText("connected");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jRadioButton2, gridBagConstraints);

        jRadioButton3.setText("alive");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jRadioButton3, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("selected player"));
        jPanel6.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(defaultCoordinateInfoComponent1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("last spawn coordinate:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jLabel2, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jLabel3, gridBagConstraints);

        jTextField1.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jTextField1, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("hive id:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jLabel4, gridBagConstraints);

        jTextField2.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jTextField2, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("identifier:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jLabel5, gridBagConstraints);

        jTextField3.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jTextField3, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("last skin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jLabel6, gridBagConstraints);

        jTextField4.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel6.add(jTextField4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jPanel5, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "connected", "disconnected"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        jTabbedPane1.addTab("server information (not yet)", jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        btnLoadRpt.setText("load RPT");
        btnLoadRpt.setMaximumSize(new java.awt.Dimension(100, 23));
        btnLoadRpt.setMinimumSize(new java.awt.Dimension(100, 23));
        btnLoadRpt.setPreferredSize(new java.awt.Dimension(100, 23));
        btnLoadRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadRptActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel7.add(btnLoadRpt, gridBagConstraints);

        txtRptPath.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel7.add(txtRptPath, gridBagConstraints);

        tgbResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/coolcow/arpiti/gui/resume.png"))); // NOI18N
        tgbResume.setEnabled(false);
        tgbResume.setFocusPainted(false);
        tgbResume.setFocusable(false);
        tgbResume.setMaximumSize(new java.awt.Dimension(100, 25));
        tgbResume.setMinimumSize(new java.awt.Dimension(100, 25));
        tgbResume.setPreferredSize(new java.awt.Dimension(100, 25));
        tgbResume.setRequestFocusEnabled(false);
        tgbResume.setRolloverEnabled(false);
        tgbResume.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/coolcow/arpiti/gui/pause.png"))); // NOI18N
        tgbResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbResumeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel7.add(tgbResume, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel7, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCopyActionPerformed
        if (popLine != null) {
            final Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            final Transferable transferable = new StringSelection(popLine.getRawLine());
            clipboard.setContents(transferable, null);
        }
    }//GEN-LAST:event_mniCopyActionPerformed

    private void tgbResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbResumeActionPerformed
        Backend.getInstance().getRptTailer().setPause(!tgbResume.isSelected());
    }//GEN-LAST:event_tgbResumeActionPerformed

    private void tgbAutoScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbAutoScrollActionPerformed
        autoscroll = tgbAutoScroll.isSelected();
    }//GEN-LAST:event_tgbAutoScrollActionPerformed

    private void btnFilterApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterApplyActionPerformed
        sorter.allRowsChanged();
        tblLines.revalidate();
    }//GEN-LAST:event_btnFilterApplyActionPerformed

    private void btnLoadRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadRptActionPerformed
        final JFileChooser fc = new JFileChooser(rptFile);
        final FileNameExtensionFilter rptFilter = new FileNameExtensionFilter("RPT file", "rpt");
        fc.setFileFilter(rptFilter);
        fc.setDialogTitle("choose RPT file");
        final int returnVal = fc.showOpenDialog(this);

        tgbResume.setEnabled(true);
        tgbResume.setSelected(true);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            rptFile = fc.getSelectedFile();
            model.clear();

            Backend.getInstance().startNewRptTailer(rptFile, new RptTailerListenerImpl());
            txtRptPath.setText(rptFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnLoadRptActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilterApply;
    private javax.swing.JButton btnLoadRpt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbFilterContent;
    private javax.swing.JCheckBox cbxFilterCleanup;
    private javax.swing.JCheckBox cbxFilterDelete;
    private javax.swing.JCheckBox cbxFilterDisconnectStartI;
    private javax.swing.JCheckBox cbxFilterDwDebugFps;
    private javax.swing.JCheckBox cbxFilterError;
    private javax.swing.JCheckBox cbxFilterHive;
    private javax.swing.JCheckBox cbxFilterLocalityEvent;
    private javax.swing.JCheckBox cbxFilterLoginAttempt;
    private javax.swing.JCheckBox cbxFilterLoginLoaded;
    private javax.swing.JCheckBox cbxFilterLoginPublishing;
    private javax.swing.JCheckBox cbxFilterNull;
    private javax.swing.JCheckBox cbxFilterObj;
    private javax.swing.JCheckBox cbxFilterPdeath;
    private javax.swing.JCheckBox cbxFilterReadWrite;
    private javax.swing.JCheckBox cbxFilterSecondHandZombieInitialized;
    private javax.swing.JCheckBox cbxFilterStartingLogin;
    private javax.swing.JCheckBox cbxFilterWrite;
    private org.coolcow.arpiti.gui.DefaultCoordinateInfoComponent defaultCoordinateInfoComponent1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JMenuItem mniCopy;
    private javax.swing.JPanel panFilter;
    private javax.swing.JPanel panInfo;
    private javax.swing.JPanel panMain;
    private javax.swing.JPanel panProgress;
    private javax.swing.JPanel panRight;
    private javax.swing.JPanel panTable;
    private javax.swing.JPanel panTypes;
    private javax.swing.JProgressBar pgbLines;
    private javax.swing.JPopupMenu pumTableitem;
    private javax.swing.JScrollPane scrTable;
    private javax.swing.JTable tblLines;
    private javax.swing.JToggleButton tgbAutoScroll;
    private javax.swing.JToggleButton tgbResume;
    private javax.swing.JTextField txtFilterContent;
    private javax.swing.JTextField txtRptPath;
    // End of variables declaration//GEN-END:variables

    static class RptTableDateCellRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(final JTable table, final Object value, final boolean isSelected, final boolean hasFocus, final int row, final int column) {
            final JComponent component;
            if (value instanceof Date) {
                component = (JComponent) super.getTableCellRendererComponent(table, new SimpleDateFormat(OUTPUT_DATE_FORMAT).format(value), isSelected, hasFocus, row, column);
            } else {
                component = (JComponent) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            }
            return component;
        }
    }

    class RptTailerListenerImpl implements RptTailerListener {

        @Override
        public void rptLinesTailed(final List<AbstractRptLine> rptLines) {
            if (rptLines != null) {
                SwingUtilities.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        model.addLines(rptLines);
                        pgbLines.setString(model.getRowCount() + " lines (" + sorter.getViewRowCount() + " filtered)");
                        if (autoscroll) {
                            try {
                                tblLines.scrollRectToVisible(tblLines.getCellRect(tblLines.getRowCount() - 1, tblLines.getColumnCount(), true));
                            } catch (final IndexOutOfBoundsException exception) {
                                LOG.warn("Error while doing autoscroll.", exception);
                            }
                        }
                    }
                });
            }
        }

        @Override
        public void tailingResumed() {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    pgbLines.setEnabled(true);
                }
            });
        }

        @Override
        public void tailingWait() {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    pgbLines.setEnabled(false);
                }
            });
        }

        @Override
        public void tailingStarted(final long byteLength) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    pgbLines.setMaximum(new Long(byteLength).intValue());
                }
            });
        }

        @Override
        public void tailingProceed(final long byteRead) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    pgbLines.setValue(new Long(byteRead).intValue());
                }
            });
        }

        @Override
        public void tailingStopped() {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    pgbLines.setEnabled(false);
                    pgbLines.setMaximum(0);
                    pgbLines.setValue(0);
                }
            });
        }
    }

    class RowFilterImpl extends RowFilter<RptLineTableModel, Integer> {

        @Override
        public boolean include(Entry<? extends RptLineTableModel, ? extends Integer> entry) {
            final RptLineTableModel model = entry.getModel();
            final AbstractRptLine line = model.getLine(entry.getIdentifier());

            final boolean contentFilterIncludes;
            final boolean typeFilterIncludes;

            if (cbFilterContent.isSelected()) {
                final String contentFilter = txtFilterContent.getText();
                if (contentFilter != null) {
                    final Pattern pattern = Pattern.compile(contentFilter);
                    contentFilterIncludes = pattern.matcher(line.getRawContent()).find();
                } else {
                    contentFilterIncludes = true;
                }
            } else {
                contentFilterIncludes = true;                
            }

            if (line.getType() == null) {
                typeFilterIncludes = cbxFilterNull.isSelected();
            } else {
                switch (line.getType()) {
                    case CLEANUP:
                        typeFilterIncludes = cbxFilterCleanup.isSelected();
                        break;
                    case DELETE:
                        typeFilterIncludes = cbxFilterDelete.isSelected();
                        break;
                    case DISCONNECT_START_I:
                        typeFilterIncludes = cbxFilterDisconnectStartI.isSelected();
                        break;
                    case ERROR:
                        typeFilterIncludes = cbxFilterError.isSelected();
                        break;
                    case HIVE:
                        typeFilterIncludes = cbxFilterHive.isSelected();
                        break;
                    case LOCALITY_EVENT:
                        typeFilterIncludes = cbxFilterLocalityEvent.isSelected();
                        break;
                    case LOGIN_ATTEMPT:
                        typeFilterIncludes = cbxFilterLoginAttempt.isSelected();
                        break;
                    case LOGIN_LOADED:
                        typeFilterIncludes = cbxFilterLoginLoaded.isSelected();
                        break;
                    case LOGIN_PUBLISHING:
                        typeFilterIncludes = cbxFilterLoginPublishing.isSelected();
                        break;
                    case OBJ:
                        typeFilterIncludes = cbxFilterObj.isSelected();
                        break;
                    case PDEATH:
                        typeFilterIncludes = cbxFilterPdeath.isSelected();
                        break;
                    case READ_WRITE:
                        typeFilterIncludes = cbxFilterReadWrite.isSelected();
                        break;
                    case STARTING_LOGIN:
                        typeFilterIncludes = cbxFilterStartingLogin.isSelected();
                        break;
                    case WRITE:
                        typeFilterIncludes = cbxFilterWrite.isSelected();
                        break;
                    case DW_DEBUG_FPS:
                        typeFilterIncludes = cbxFilterDwDebugFps.isSelected();
                        break;
                    case SECOND_HAND_ZOMBIE_INITIALIZED:
                        typeFilterIncludes = cbxFilterSecondHandZombieInitialized.isSelected();
                        break;
                    default:
                        typeFilterIncludes = true;
                }
            }
            
            return contentFilterIncludes && typeFilterIncludes;
        }
    }

    class RptTableMouseListener extends MouseAdapter {

        @Override
        public void mouseReleased(final MouseEvent event) {

            if (event.isPopupTrigger()) {
                final int row = tblLines.rowAtPoint(event.getPoint());
                if (row >= 0 && row < tblLines.getRowCount()) {
                    tblLines.setRowSelectionInterval(row, row);
                } else {
                    tblLines.clearSelection();
                }

                int rowindex = tblLines.getSelectedRow();

                if (rowindex >= 0 && event.isPopupTrigger() && event.getComponent() instanceof JTable) {
                    popLine = (AbstractRptLine) model.getLine(tblLines.convertRowIndexToModel(row));
                    pumTableitem.show(event.getComponent(), event.getX(), event.getY());
                }
            }
        }
    }

    class RptTableSelectionListener implements ListSelectionListener {

        @Override
        public void valueChanged(final ListSelectionEvent event) {
            panInfo.removeAll();
            final int row = tblLines.getSelectedRow();
            if (row >= 0) {
                final AbstractRptLine rptLine = model.getLine(tblLines.convertRowIndexToModel(row));
                final AbstractRptLineRenderer renderer = RptLineRendererProvider.getRenderer(rptLine.getType());
                renderer.setRptLine(rptLine);
                panInfo.add(renderer);
            }
            panInfo.validate();
            panInfo.repaint();
        }
    }

    static class CorrectLayoutJTable extends JTable {

        @Override
        public void doLayout() {
            if (getTableHeader().getResizingColumn() == null) {
                if (getAutoResizeMode() == JTable.AUTO_RESIZE_LAST_COLUMN) {
                    getTableHeader().setResizingColumn(getColumnModel().getColumn(getColumnModel().getColumnCount() - 1));
                }
            }
            super.doLayout();
        }
    }
}
